(function(){'use strict';
const URL='https://ofskkihaffiaaxmzbntc.supabase.co',KEY='sb_publishable_gUdMHwTb2_Y491ufzU860w_H-oHPvID',SK='montage-supabase-session';let session=null,isClient=false,timer;document.getElementById('app').style.visibility='hidden';
const css=document.createElement('style');css.textContent=`.cloud-auth{position:fixed;inset:0;z-index:100;background:rgba(245,245,247,.94);backdrop-filter:blur(24px);display:grid;place-items:center;padding:20px}.cloud-auth.hidden{display:none}.cloud-card{width:min(390px,100%);background:#fff;border-radius:24px;padding:28px;box-shadow:0 20px 70px #0002}.cloud-card h1{font:650 30px -apple-system,sans-serif;letter-spacing:-.04em;margin:12px 0 6px}.cloud-card p{color:#6e6e73}.cloud-card input{width:100%;height:48px;margin:6px 0;border:1px solid #d2d2d7;border-radius:12px;padding:0 14px;font-size:16px}.cloud-login{width:100%;height:44px;margin-top:10px;border:0;border-radius:999px;background:#0071e3;color:#fff;font-weight:650}.cloud-message{min-height:20px;font-size:12px!important}.cloud-user{position:fixed;right:18px;bottom:18px;z-index:20;background:#fffffff0;box-shadow:0 5px 22px #0002;border-radius:999px;padding:7px 9px 7px 13px;font-size:11px;color:#6e6e73}.cloud-user button,.cloud-edit{border:0;background:#eeeef0;border-radius:999px;padding:7px 10px;margin-left:8px;cursor:pointer}.cloud-edit{margin:7px 0 0;font-size:10px}.client-panel{min-height:100vh;background:#f5f5f7;padding:42px max(18px,5vw) 100px;color:#1d1d1f}.client-wrap{max-width:900px;margin:auto}.client-head small{color:#6e6e73;font-weight:650}.client-head h1{font:650 clamp(34px,7vw,64px) -apple-system,sans-serif;letter-spacing:-.055em;margin:8px 0 28px}.client-total{background:#1d1d1f;color:#fff;border-radius:26px;padding:24px 26px;margin-bottom:16px}.client-total span{font-size:12px;color:#a1a1a6}.client-total b{display:block;font:650 clamp(38px,8vw,68px) -apple-system,sans-serif;letter-spacing:-.05em;margin-top:6px}.client-job{background:#fff;border-radius:18px;padding:17px 19px;margin:10px 0;display:grid;grid-template-columns:1fr auto;gap:8px 20px;box-shadow:0 3px 16px #0001}.client-job strong{font-size:18px}.client-job span{grid-column:1/-1;color:#6e6e73;font-size:12px}.client-empty{background:#fff;border-radius:18px;padding:34px;text-align:center;color:#6e6e73}@media(max-width:570px){.cloud-user{left:12px;right:12px;bottom:10px;text-align:center}.client-job{grid-template-columns:1fr}.client-job span{grid-column:auto}}`;document.head.appendChild(css);
const auth=document.createElement('section');auth.className='cloud-auth';auth.innerHTML=`<form class="cloud-card" id="cloudAuthForm"><div class="logo">M</div><h1>Облачный вход</h1><p>Одна учётная запись работает на телефоне и компьютере.</p><input id="cloudEmail" autocomplete="username" placeholder="Логин или почта" required><input id="cloudPassword" type="password" minlength="6" autocomplete="current-password" placeholder="Пароль" required><button class="cloud-login">Войти</button><p class="cloud-message" id="cloudMessage"></p></form>`;document.body.appendChild(auth);
const badge=document.createElement('div');badge.className='cloud-user';badge.style.display='none';badge.innerHTML=`<span id="cloudUserEmail"></span><button id="cloudLogout">Выйти</button>`;document.body.appendChild(badge);
async function request(path,o={}){const r=await fetch(URL+path,o),raw=await r.text();let d;try{d=raw?JSON.parse(raw):null}catch{d=raw}if(!r.ok)throw Error(d?.msg||d?.message||d?.error_description||`Ошибка ${r.status}`);return d}
const hdr=(extra={})=>({apikey:KEY,Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json',Prefer:'return=representation',...extra});
async function cloud(path,o={}){return request('/rest/v1/'+path,{...o,headers:hdr(o.headers)})}function store(v){session=v;v?localStorage.setItem(SK,JSON.stringify(v)):localStorage.removeItem(SK)}
const from=r=>({id:r.id,date:r.work_date,title:r.title,total:r.total_seconds,ads:r.ad_seconds,paid:r.paid}),to=j=>({work_date:j.date,title:j.title,total_seconds:j.total,ad_seconds:j.ads,paid:j.paid}),mins=j=>Math.ceil(Math.max(0,j.total-j.ads)/60);
async function settings(){if(!session?.user?.id||isClient)return;await cloud('montage_settings?on_conflict=user_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({user_id:session.user.id,rate:+$('rate').value||250,compare_rate:+$('compare').value||350,updated_at:new Date().toISOString()})})}
async function load(){const a=await cloud(`montage_access?select=role&viewer_id=eq.${encodeURIComponent(session.user.id)}`,{method:'GET'});isClient=a.some(x=>x.role==='client');let rows=await cloud('montage_jobs?select=*&order=work_date.desc,created_at.desc',{method:'GET'});if(!isClient&&!rows.length&&jobs.length){await cloud('montage_jobs',{method:'POST',body:JSON.stringify(jobs.map(to))});rows=await cloud('montage_jobs?select=*&order=work_date.desc,created_at.desc',{method:'GET'})}jobs=rows.map(from);const s=await cloud('montage_settings?select=*&limit=1',{method:'GET'});if(s[0]){$('rate').value=s[0].rate;$('compare').value=s[0].compare_rate}else if(!isClient)await settings();if(isClient)client();else{render();renderExtras();decorate();$('app').style.visibility='visible'}}
function show(){auth.classList.add('hidden');badge.style.display='';let e=session.user?.email||'Supabase';$('cloudUserEmail').textContent=e.endsWith('@montage.local')?e.split('@')[0]:e}function error(e){$('cloudMessage').textContent=e.message||e}
$('cloudAuthForm').onsubmit=async e=>{e.preventDefault();let b=e.submitter;b.disabled=true;$('cloudMessage').textContent='Подключение…';let l=$('cloudEmail').value.trim().toLowerCase(),email=l.includes('@')?l:`${l}@montage.local`;try{store(await request('/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({email,password:$('cloudPassword').value})}));show();await load()}catch(x){error(x)}finally{b.disabled=false}};$('cloudLogout').onclick=()=>{store(null);location.reload()};
function install(){$('form').onsubmit=async e=>{e.preventDefault();if(isClient)return;let total=time('totalMin','totalSec'),ads=time('adsMin','adsSec');if(!total||ads>total)return alert('Проверьте тайминг');try{let [r]=await cloud('montage_jobs',{method:'POST',body:JSON.stringify(to({date:$('date').value,title:$('title').value.trim()||'Ролик без названия',total,ads,paid:false}))});jobs.unshift(from(r));$('title').value='';['totalMin','totalSec','adsMin','adsSec'].forEach(i=>$(i).value='');calc();render();renderExtras();decorate()}catch(x){alert(x.message)}};window.toggle=async id=>{if(isClient)return;let j=jobs.find(x=>x.id===id);if(!j)return;let[r]=await cloud(`montage_jobs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({paid:!j.paid,updated_at:new Date().toISOString()})});jobs=jobs.map(x=>x.id===id?from(r):x);render();renderExtras();decorate()};window.del=async id=>{if(isClient||!confirm('Удалить этот ролик?'))return;await cloud(`montage_jobs?id=eq.${encodeURIComponent(id)}`,{method:'DELETE'});jobs=jobs.filter(x=>x.id!==id);render();renderExtras();decorate()}}
window.editCloudJob=async id=>{if(isClient)return;let j=jobs.find(x=>x.id===id);if(!j)return;let title=prompt('Название ролика',j.title);if(title===null)return;let date=prompt('Дата ГГГГ-ММ-ДД',j.date);if(date===null)return;let tm=prompt('Общий тайминг — минуты',Math.floor(j.total/60));if(tm===null)return;let ts=prompt('Общий тайминг — секунды',j.total%60);if(ts===null)return;let am=prompt('Реклама — минуты',Math.floor(j.ads/60));if(am===null)return;let as=prompt('Реклама — секунды',j.ads%60);if(as===null)return;let total=+tm*60+ +ts,ads=+am*60+ +as;if(!total||ads>total)return alert('Проверьте тайминг');let[r]=await cloud(`montage_jobs?id=eq.${encodeURIComponent(id)}`,{method:'PATCH',body:JSON.stringify({work_date:date,title:title.trim()||'Ролик без названия',total_seconds:total,ad_seconds:ads,updated_at:new Date().toISOString()})});jobs=jobs.map(x=>x.id===id?from(r):x).sort((a,b)=>b.date.localeCompare(a.date));render();renderExtras();decorate()};
function decorate(){if(isClient)return;document.querySelectorAll('#list .row').forEach(row=>{let s=row.querySelector('.status'),x=row.querySelector('.x'),m=s?.getAttribute('onclick')?.match(/toggle\(([^)]+)\)/);if(!m)return;let id=m[1].replace(/["']/g,'');s.removeAttribute('onclick');s.onclick=()=>window.toggle(id);x?.removeAttribute('onclick');if(x)x.onclick=()=>window.del(id);let b=document.createElement('button');b.className='cloud-edit';b.textContent='Изменить';b.onclick=()=>editCloudJob(id);row.querySelector('.info')?.appendChild(b)})}
function client(){$('app').style.display='none';let p=document.querySelector('.client-panel')||document.body.appendChild(document.createElement('main'));p.className='client-panel';let rate=+$('rate').value||250,u=jobs.filter(j=>!j.paid),total=u.reduce((s,j)=>s+mins(j)*rate,0);p.innerHTML=`<div class="client-wrap"><div class="client-head"><small>PROАВТО · КАБИНЕТ ЗАКАЗЧИКА</small><h1>К оплате</h1></div><section class="client-total"><span>${u.length} роликов</span><b>${rub(total)}</b></section>${u.length?u.map(j=>`<article class="client-job"><b>${j.title.replace(/[<>]/g,'')}</b><strong>${rub(mins(j)*rate)}</strong><span>${new Date(j.date+'T12:00').toLocaleDateString('ru-RU')} · ${mins(j)} мин · ${rate} ₽/мин</span></article>`).join(''):'<div class="client-empty"><b>Всё оплачено</b><p>Сейчас задолженности нет.</p></div>'}</div>`}
['rate','compare'].forEach(id=>$(id).addEventListener('input',()=>{if(isClient)return;clearTimeout(timer);timer=setTimeout(()=>settings().catch(console.error),600)}));new MutationObserver(decorate).observe($('list'),{childList:true,subtree:true});install();try{session=JSON.parse(localStorage.getItem(SK))}catch{}if(session?.access_token&&session?.user){show();load().catch(e=>{store(null);auth.classList.remove('hidden');error(e)})}
})();
